server:
  port: 8083
  
spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    
keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: sripiranavan
      password: pass
    realmImportFile: sri-realm.json
